# Site settings
title: Megan Naccarato
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Watercolor art by Megan Naccarato
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://artbymegannacc.com/" # the base hostname & protocol for your site
twitter_username: 
dribbble_username: megannacc

# Build settings
markdown: kramdown
permalink: pretty
